name: WorldLock
version: '${version}'
main: host.plas.worldlock.WorldLock
folia-supported: true
authors: [ Drak ]
depend:
  - BukkitOfUtils

commands:
  manageworlds:
    description: Manage worlds
    aliases:
      - mw
    permission: worldlock.command.manageworlds