name: WorldLock
version: '${version}'
main: host.plas.worldlock.WorldLock

commands:
  manageworlds:
    description: Manage worlds
    aliases:
      - mw
    permission: worldlock.command.manageworlds